apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployemt
  labels:
    app: react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app
        image: gaurav714/react_repo:01
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-service
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer